table Dim_Product
	lineageTag: 9efe9482-4129-4083-9740-9e1b6dd032be

	column Item
		dataType: string
		lineageTag: c66ed33e-fe9a-40a0-a008-40870ccdc796
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 30726e86-8b8b-4ca4-93f7-dfdffbc29262
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: int64
		formatString: 0
		lineageTag: 848c8cc8-acb9-448d-bde8-f221b1cd37fa
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Fact_Sales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"item", "category", "unit_price"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"item", "Item"}, {"category", "Category"}, {"unit_price", "Unit Price"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

